CREATE TABLE IF NOT EXISTS stockactivitylog (
    logid INT AUTO_INCREMENT PRIMARY KEY,
    batchid VARCHAR(50),
    dateofarrival DATE,
    dateencoded DATETIME DEFAULT CURRENT_TIMESTAMP,
    encoder VARCHAR(50),
    description TEXT,
    totalNumberOfBoxes INT DEFAULT 0,
    overalltotalweight DECIMAL(10,2) DEFAULT 0.00,
    activity_type VARCHAR(20),
    productcode VARCHAR(50),
    productname VARCHAR(100),
    quantity_changed INT DEFAULT 0,
    movement_type ENUM('IN', 'OUT', 'ADJUSTMENT') DEFAULT NULL,
    performed_by VARCHAR(50),
    details TEXT,
    totalpacks INT DEFAULT 0,
    unit_price DECIMAL(10,2) DEFAULT 0.00,
    total_value DECIMAL(10,2) GENERATED ALWAYS AS (quantity_changed * unit_price) STORED,
    INDEX idx_date (dateencoded),
    INDEX idx_batch (batchid),
    INDEX idx_product (productcode),
    INDEX idx_activity (activity_type),
    INDEX idx_movement (movement_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
