CREATE TABLE IF NOT EXISTS users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    useremail VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    role ENUM('admin', 'supervisor', 'ceo') NOT NULL,
    department VARCHAR(50),
    status ENUM('active', 'inactive', 'suspended') DEFAULT 'active',
    is_online BOOLEAN DEFAULT FALSE,
    last_online DATETIME,
    failed_login_attempts INT DEFAULT 0,
    last_failed_login DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_password_change DATETIME,
    password_reset_token VARCHAR(100),
    password_reset_expires DATETIME,
    INDEX idx_email (useremail),
    INDEX idx_username (username),
    INDEX idx_role (role),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 